#pragma once

// From glfw3.h
#define SB_MOUSE_BUTTON_1 0
#define SB_MOUSE_BUTTON_2 1
#define SB_MOUSE_BUTTON_3 2
#define SB_MOUSE_BUTTON_4 3
#define SB_MOUSE_BUTTON_5 4
#define SB_MOUSE_BUTTON_6 5
#define SB_MOUSE_BUTTON_7 6
#define SB_MOUSE_BUTTON_8 7
#define SB_MOUSE_BUTTON_LAST SB_MOUSE_BUTTON_8
#define SB_MOUSE_BUTTON_LEFT SB_MOUSE_BUTTON_1
#define SB_MOUSE_BUTTON_RIGHT SB_MOUSE_BUTTON_2
#define SB_MOUSE_BUTTON_MIDDLE SB_MOUSE_BUTTON_3